### ISSUE TITLE
Wrong filename ...

### ISSUE THREAD

**Issue by grekpg** [anthony-mills/panoramio#3]
File names should match class names, so if you are trying to load mills\panoramio\panoramioAPI, the filename should be panomarioAPI.php

use mills\panoramio\panoramioAPI;
$panoramioClass = new panoramioAPI();
Fatal error: Class 'mills\panoramio\panoramioAPI' not found in ..

**Comment by anthony-mills** [comment]
Thanks mate well spotted.
